import os


# Snowflake configuration. Replace it with your snowflake warehouse configuration.
SNOWFLAKE_ACCOUNT="XAA48144"
SNOWFLAKE_USER="ACRYL_TAKE_HOME"
SNOWFLAKE_PASSWORD="ytw5vxw*FAW2hyn7nqh"
SNOWFLAKE_ROLE="LONG_TAIL_READ_ONLY"
SNOWFLAKE_WAREHOUSE="COMPUTE_WH"
SNOWFLAKE_DATABASE="LONG_TAIL_COMPANIONS"