import os


# Snowflake configuration. Replace it with your snowflake warehouse configuration.
SNOWFLAKE_ACCOUNT="<SNOWFLAKE_ACCOUNT>"
SNOWFLAKE_USER="<SNOWFLAKE_USER>"
SNOWFLAKE_PASSWORD="<SNOWFLAKE_PASSWORD>"
SNOWFLAKE_ROLE="<SNOWFLAKE_ROLE>"
SNOWFLAKE_WAREHOUSE="<SNOWFLAKE_WAREHOUSE>"
SNOWFLAKE_DATABASE="<SNOWFLAKE_DATABASE>"